### ISSUE TITLE
Spacebar doesn't make it fly

### ISSUE THREAD

**Issue by dusave** [matthock/HoverPackExtensions#1]
Tested the v1 vs v2 jetpack to make sure I wasn't crazy, but the v2 doesn't seem to want to do anything.

**Comment by matthock** [comment]
Are you running in single player or multiplayer? There's a bug with the current version of Satisfactory Mod Loader that causes mods to not work in multiplayer. The fix for that is just now getting tested in Experimental, but is not yet released in Early Access, so I can't fix multiplayer compatibility until they finish that.

**Comment by dusave** [comment]
I am running in single player

**Comment by matthock** [comment]
Steam or Epic? Any other mods installed? I'll need to try to reproduce your setup on my end.

**Comment by dusave** [comment]
Epic, and yes other mods. I've attached my SMM profile if that helps
[Mods.zip](https://github.com/matthock/HoverPackExtensions/files/6416800/Mods.zip)

**Comment by matthock** [comment]
Thanks, I'll take a look at it and see if one of the others is conflicting.

**Comment by matthock** [comment]
Haven't been able to reproduce the problem so far. One thing I did notice - you said Jetpack above, and I notice your mod list had the Jet Pack Mk2 mod installed. That's a different mod from this one. Can you double check that it's the Hover Pack Mk2 that isn't responding to controls and not Jet Pack Mk2? If the mod list you sent me is your latest set up, it also did not show Hover Pack Mk2 installed on your save.

If it is, the next thing to check is the Pak Utilities Mod does have some commands that can temporarily alter keybinds. Before equipping the Hover Pack Mk2, try toggling the !fly command on and off, and make sure it's Off when you put on the pack. This didn't actually make a difference on my end, but I could see something getting stuck in more extended use and toggling potentially helping.

**Comment by dusave** [comment]
..... 🤦🏻‍♂️  I'm just gonna see myself out... 

Sorry about that, I searched the wrong one on SMR 😆

**Comment by matthock** [comment]
No worries, it's easy enough to get the two confused :D
